language: node_js
node_js: stable

cache:
    apt: true
    directories:
        - node_modules # 缓存不经常更改的内容

before_install:
    - export TZ='Asia/Shanghai' # 更改时区

# S: Build Lifecycle
install:
  - npm install


#before_script:
 # - npm install -g gulp

script:
  - hexo clean  #清除
  - hexo g

# 执行的命令
script:
- hexo clean
- hexo generate
# 执行的成功后执行 
after_success:
- hexo deploy
# E: Build LifeCycle

branches:
  only:
    - fzq
env:
 global:
   - GH_REF: github.com/asmysoul/asmysoul.github.io.git